name: Deploy

on:
  push:
    branches:
      - master
      - source
  pull_request:
    branches:
      - master
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then # branch, e.g., master, source, etc.
          # Remove 'refs/heads/' prefix from GITHUB_REF
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        if [[ "${GITHUB_REPOSITORY}" == *.github.io ]]; then # user/org repo
          echo "DEPLOY_BRANCH=master" >> $GITHUB_OUTPUT
        else
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT
        fi

    - name: Deploy website
      run: |
        yes | bin/deploy --verbose \
          ${{ steps.setup.outputs.NO_PUSH }} \
          --src "${{ steps.setup.outputs.SRC_BRANCH }}" \
          --deploy "${{ steps.setup.outputs.DEPLOY_BRANCH }}"
